title: Marina Kuzminchuk
description: My designs are rooted in user research while expressing values through a distinct visual identity.
url: "https://marinakuzminchuk.github.io"
baseurl: ""

permalink: pretty

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
